on:
  pull_request:
    branches:
      - main

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04
  
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install
    - run: npm lint
    - run: npm test
